
version: "3.9"

services:
  db:
    image: postgres
    environment:
        POSTGRES_PASSWORD: password
        POSTGRES_USER: user
        POSTGRES_DB: postgres
    networks:
      - app-network

  adminer:
    image: adminer
    ports:
      - "8081:8081"
    networks:
      - app-network

  app:
    stdin_open: true
    build:
      context: .
      target: dev
    ports:
      - "8001:8001"
    env_file: .env
    depends_on:
      - db
    command: >
      bash -c "/app/tada/scripts/wait-for-it db:5432 && alembic upgrade head && uvicorn tada.src.main:app --host 0.0.0.0 --port 8001 --reload"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
